import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')

if not GetDepend(['RT_USING_FAL']):
    SrcRemove(src, ['ota_partition.c'])

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
