#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

#define SOC_VEXPRESS_A9_BOOT

#define RT_NAME_MAX 8
#define RT_CPUS_NR 1
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_USING_DEBUG
#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP
#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 128
#define RT_CONSOLE_DEVICE_NAME "uart0"
#define RT_VER_NUM 0x50200
#define RT_BACKTRACE_LEVEL_MAX_NR 32
#define RT_USING_HW_ATOMIC
#define RT_USING_CPU_FFS
#define ARCH_ARM
#define ARCH_ARM_MMU
#define ARCH_ARM_CORTEX_A
#define ARCH_ARM_CORTEX_A9
#define ARCH_MM_MMU
#define RT_USING_CACHE
#define RT_USING_GIC_V2

#define RT_USING_RESOURCE_ID
#define RT_USING_ADT
#define RT_USING_ADT_AVL

#define RT_PAGE_AFFINITY_BLOCK_SIZE 0x1000
#define RT_PAGE_MAX_ORDER 11

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 1024
#define RT_MAIN_THREAD_PRIORITY 10

#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_RB_BUFSZ 64
#define RT_USING_DEVICE_IPC

#define SOC_VEXPRESS_A9
#define RT_USING_UART0
#define BSP_USING_NOR_FLASH0
#define BSP_USING_FAL

#define RT_USING_FAL
#define FAL_PART_HAS_TABLE_CFG
#define FAL_DEBUG 0

#define PKG_USING_QBOOT
#define QBOOT_APP_PART_NAME "app"
#define QBOOT_DOWNLOAD_PART_NAME "download"
#define QBOOT_FACTORY_PART_NAME "factory"
#define QBOOT_USING_QUICKLZ
#define QBOOT_THREAD_STACK_SIZE 4096
#define QBOOT_THREAD_PRIO 5
#define PKG_QBOOT_VER "latest"

#define PKG_USING_CRCLIB
#define PKG_USING_CRCLIB_V102
#define CRCLIB_USING_CRC32
#define CRC32_USING_CONST_TABLE

#define PKG_USING_QUICKLZ
#define PKG_USING_QUICKLZ_V101

#define PKG_USING_FAL

#endif
