from building import *
import os
import rtconfig

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd, os.path.join(cwd, '..')]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang', 'llvm-arm']:
    LOCAL_CFLAGS += ' -std=c99'

group = DefineGroup('FAL', src, depend=['RT_USING_FAL'], CPPPATH=CPPPATH, LOCAL_CFLAGS=LOCAL_CFLAGS)

Return('group')
